[base]
pidfile = "/tmp/job.pid"
hostAddr = "0.0.0.0:8080"
redisAddr = "127.0.0.1:6379"
redisPw = "123456"
usePool = 1
poolSize = 100


[[workerAddrs]]
key = 1
addr = "tcp@172.18.12.226:8848"

[[workerAddrs]]
key = 2
addr = "tcp@0.0.0.0:8849"

[etcd]
host = "127.0.0.1:2379"
basePath = "/imgo_rpcx"
ServerPathDispatcher = "PushRpc"