[base]
pidfile = "/tmp/worker.pid"
logfile = "../logs/worker.log"
serverId = "1"
PprofBind = "0.0.0.0:7777"
RedisAddr = "localhost:6379"
redisPw = "123456"
RedisDefaultDB = 0
RedisPoolSize = 200
RedisKeyTtl = 7200

[websocket]
bind = "0.0.0.0:8989"
beatingInterval = 60
retransInterval = 18

[[rpcPushAddrs]]
key = 1
addr = "tcp@0.0.0.0:8848"
inner = "127.0.0.1:8848"

[etcd]
host = [
       	"172.18.12.226:2379",
       	"172.18.12.229:2379",
       	"172.18.12.254:2379"
       ]
basePath = "/imgo_rpcx"
serverPathWorker = "PushRpc"